apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ldap-auth

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - issuer.yaml
  - certificate.yaml
  - health-check.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - redis-pvc.yaml
  - networkpolicy.yaml
  - poddisruptionbudget.yaml
  - servicemonitor.yaml
