apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ldap-auth-dev

namePrefix: dev-
nameSuffix: ""

commonLabels:
  environment: dev

resources:
- ../../base

patches:
- path: deployment-patch.yaml
- path: hpa-patch.yaml

configMapGenerator:
- name: ldap-auth-config
  behavior: merge
  literals:
  - LOG_LEVEL=debug
  - RUST_LOG=ldap_auth_rs=debug,tower_http=debug

images:
- name: ldap-auth-rs
  newTag: dev

replicas:
- name: ldap-auth-rs
  count: 1
